# Generated by Django 4.2.1 on 2023-07-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField()),
                ('owner', models.CharField(max_length=30)),
                ('listing', models.IntegerField()),
            ],
        ),
    ]
