# Generated by Django 4.2.1 on 2023-07-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='products',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='products',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listings'),
            preserve_default=False,
        ),
    ]
