# Generated by Django 4.2.1 on 2023-07-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_watchlists_products_watchlists_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='products',
        ),
        migrations.AddField(
            model_name='watchlists',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.listings'),
        ),
    ]
